# Generated by Django 4.0.1 on 2022-02-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileInfo", "0002_portfolio_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="to_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
